### ISSUE TITLE
Expand error message for `col_select`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#134]
A `col_select` error currently warns if a column could not be found (👍):

> Can't find column(s) `animal-id` in schema.

The user might not necessarily know what columns are available, so it would be helpful to show those:

> Can't find column(s) `animal-id`, `vis` in field names.
> ℹ Field names: `event-id`, `visible`, `timestamp`, `location-long`, `location-lat`, `bar:barometric-pressure`, `external-temperature`, `gps:dop`, `gps:satellite-count`, `gps-time-to-fix`, `ground-speed`, `heading`, `height-above-msl`, `import-marked-outlier`, `location-error-numerical`, `manually-marked-outlier`, `vertical-error-numerical`, `sensor-type`, `individual-taxon-canonical-name`, `tag-local-identifier`, `individual-local-identifier`, `study-name`

I also rephrased the first sentence, to mention the word "field names". I think it is less important to mention "schema".

**Comment by PietrH** [comment]
I discovered something interesting, R will output something different depending on if you specify the unicode symbol "information source" by it's hex code  `"\u2139"` or by typing it directly (or pasting it) `"ℹ️"`. 

These display differently, and R doesn't consider them the same:

``` r
"\u2139"
#> [1] "ℹ"

"ℹ️"
#> [1] "ℹ️"

"ℹ️" == "\u2139"
#> [1] FALSE
```

<sup>Created on 2023-04-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is because they have a different [variation form](https://en.wikipedia.org/wiki/Variant_form_(Unicode)) specified, the first in text representation mode, the second using variation selector sequence 16 ([ref](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block))) 

The symbol we are using is even an example on wikipedia: https://en.wikipedia.org/wiki/Emoji#Emoji_versus_text_presentation

So both characters are the same, but different. 

----

Anyway, we should pick if we want to use text or emoji presentation, I don't know what the fallback is when the emoji is unavailable, I suspect text mode. 

----

I actually really like how the emoji displays. Using text representation is probably more defensive. Any opinions? 

### Emoji
![image](https://user-images.githubusercontent.com/48065851/229766541-1d260a03-680d-4273-954c-7c9393de3793.png)
### Text Mode
![image](https://user-images.githubusercontent.com/48065851/229766693-b3d9cb1f-5bed-4156-8b46-900444f8b37e.png)

**Comment by peterdesmet** [comment]
I think we should use text mode. I've encountered R CMD Check issues regarding "not ascii" when I relied on the emoji symbol.
