### ISSUE TITLE
Don't add `tabular-data-package` as profile with `create_package()` or move it to `write_package()`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#186]
`create_package()` currently adds `"profile": "tabular-data-package"` if not `profile` is set yet. A [Tabular Data Package](https://specs.frictionlessdata.io/tabular-data-package/#specification) requires:

> There MUST be at least one resource in the resources array.

This is invalid after `create_package()`, since resources are not added yet. `write_package()` will check that resources are not empty, `check_package()` does not.

> There MUST be a `profile` property with the value `tabular-data-package`

This is self referential: if `profile` is not set, it won't fail. A package without a profile is considered a (regular) data package.

> Each resource MUST be a [Tabular Data Resource](https://specs.frictionlessdata.io/tabular-data-resource/)

This is defined at the resource, not package level. `read_resource()` expects it, `add_resource()` will add it.

I therefore think that setting `"profile"="tabular-data-package"` is somewhat useless. I would not set it all. If there are strong arguments to do so, I would set it in `write_package()`, not `create_package()`.

@khusmann thoughts?

Note to self: also update `example_datapackage`

**Comment by khusmann** [comment]
> This is invalid after `create_package()`, since resources are not added yet. `write_package()` will check that resources are not empty, `check_package()` does not.

I think in general, this is why builder type patterns are nice. So rather than constructing actual `DataPackage` object with `create_package()`, we have it create an intermediate `DataPackageBuilder` which allows us to chain settings & resources to, and allowed to hold an incomplete / contradictory state, because it's just accumulating the settings we give it.  This also enables us to load the settings in with any order.

But then finally a call to `to_descriptor()` or `write()` or whatever would give us the final DataPackage descriptor (and validate at that time)

> I would not set it all. If there are strong arguments to do so, I would set it in `write_package()`, not `create_package()`.

Without an intermediate "builder" object approach, I think this makes the most sense so you have a valid DataPackage object at each step of the way, as you say.

That all said, I don't have a strong attachment to `profile: tabular-data-package`, because it seems somewhat limiting to constrain to all tabular data resources (what if you want to include scripts or README or something?).  I think `profile: tabular-data-resource` is much more useful in practice.

**Comment by peterdesmet** [comment]
Thanks! I’m happy with the current design of having a ( tabular-data-package incomplete) package object that is passed around between functions. The (data-package) necessary checks are done by calling `check_package()` at the start of each function, providing users with a helpful error.

> I think profile: `tabular-data-resource` is much more useful in practice.

I agree, maybe we should bring it up in the specs to just deprecate the whole `tabular-data-package` spec?

**Comment by khusmann** [comment]
> I agree, maybe we should bring it up in the specs to just deprecate the whole tabular-data-package spec?

Hmm yeah, it's probably worth a mention at some point to see what others think -- I know I wouldn't be opposed to deprecating it!

**Comment by peterdesmet** [comment]
Implemented in https://github.com/frictionlessdata/frictionless-r/issues/186
