### ISSUE TITLE
Cache profiles

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#202]
`profile` properties are a URL to a version of a profile and could therefore be cached. That would allow users to read the profile just once, but from then on, no longer require an internet connection to read a resource.

See the recommendation at https://datapackage.org/standard/glossary/#profile

**Comment by peterdesmet** [comment]
Note, we used caching in camtrapdp using memoise: https://github.com/inbo/camtrapdp/pull/67. It's a good starting point for implementing this.

**Comment by PietrH** [comment]
Before memoisation, it takes around 13.5 seconds to run all tests on office internet: 

```
Unit: seconds
             expr      min       lq    mean   median       uq      max neval
 devtools::test() 12.92336 13.13131 13.3904 13.19039 13.62471 14.43051    10
```

**Comment by PietrH** [comment]
Where exactly does profile get read from an url?

**Comment by peterdesmet** [comment]
Where can we use memoise:

❌ Data Resource `profile`: ignored
✅ `datapackage.json`: read with `read_descriptor()`
❌ Data Resource `profile`: must be the string `tabular-data-resource` (but will be deprecated), never a URL
✅ Data Resource `schema`: read with `read_descriptor()`
✅ Data Resource `dialect`: read with `read_descriptor()`

So we could implement memoise in `read_descriptor()`:

https://github.com/frictionlessdata/frictionless-r/blob/27a5c692a39a633698929c7decbf3ad686761237/R/utils.R#L64-L78

**Comment by PietrH** [comment]
Thank you! I'll get on it!

**Comment by PietrH** [comment]
If the same argument values are passed to memoised functions, the cached result is returned. 

Which means that if the path to `datapackage.json` hasn't changed, any changes to the datapackage since the last read will not be present in the returned objects. 

With this in mind, we are abandoning the idea of caching reading from both local paths and urls, instead we'd consider caching when we read profiles, however, we don't use profiles in frictionless-r at the moment. So at the moment we will not be adding memoisation to frictionless-r. 

At the moment, the code in the branch attached to this issue will use cached versions of any paths passed to `read_descriptor()`, it would be safer to only do this for urls. But since we are abandoning the whole idea I didn't implement this.
