### ISSUE TITLE
Specify what we need from rlang

### ISSUE THREAD

**Issue by damianooldoni** [frictionlessdata/frictionless-r#232]
In `read_resource()` we use the `%||` operator, called the "default" or "null-coalescing" operator. It is used for the first time in [L224](https://github.com/frictionlessdata/frictionless-r/blob/main/R/read_resource.R#L224).

This operator was first introduced in the rlang package. It was later incorporated into base R with the release of R 4.4.0.

As @peterdesmet noticed during the code sprint, we import rlang entirely: see [frictionless-package.R#L4](https://github.com/frictionlessdata/frictionless-r/blob/main/R/frictionless-package.R#L4). However, by doing this it results less clear what is exactly imported from rlang.

Changing `#' @import rlang` with `#' @importFrom rlang %||%` works well: no RCMD CHECK errors with 4.3.2 and  4.4.1.

@peterdesmet: is it ok if I do a very small PR for this?

**Comment by peterdesmet** [comment]
Sure!

**Comment by peterdesmet** [comment]
This should be reassessed, since we also use `{{ ... }}` from rlang.

**Comment by khusmann** [comment]
I agree with this being reassessed -- I [originally advocated for the blanket rlang import](https://github.com/frictionlessdata/frictionless-r/issues/175#issuecomment-2018881182). Most tidyverse packages do this because it provides a number of replacements to low-level base-r functions that can really improve quality of life (e.g. `names2(), `set_names()`, `inject()`, `has_names()`, etc. etc.) that are really nice to be available in the global namespace. But I understand if you're wanting to track your deps and/or are hesitant to buy in to the entire rlang.

**Comment by peterdesmet** [comment]
#234 was [reverted](https://github.com/frictionlessdata/frictionless-r/commit/d0678e5f5376542b8cc02f3b04b40da1f0cc31cf) to blanket rlang import, since `{{ }}` cannot be imported.

The end result is that this issue was not implemented.
