### ISSUE TITLE
Set minimum R dep to R3.6.0 (originally R4.0 was suggested)

### ISSUE THREAD

**Issue by PietrH** [frictionlessdata/frictionless-r#238]
Context: #235

We've decided to up the minimum dependency to R4.0.0, so we can use native pipes and to follow the tidyverse policy: https://www.tidyverse.org/blog/2019/04/r-version-support/

In the discussion I linked to in #235 for the `evaluate` package, Hadley Wickam decides to set the minimum requirement there as R4.0.0, but then later on changes his mind back to R3.6, which is what it currently is for the dev version. 

The packages that are dependencies of `testthat` will continue working on R3.6 minimum, the other tidyverse packages will soon change to R4.0 minimum. 

So the reasoning is that we go to R4.0 minimum to stay in line with the tidyverse. 

- [x] Update DESCRIPTION
- [x] Create CI action
- [x] Remove usage of `...names()`

**Comment by peterdesmet** [comment]
Since frictionless is designed as a dependency for other packages, it's likely good to support as many versions of R as possible. bioRad for example, which depends on frictionless, has `Depends: R (>= 3.5.0)` https://github.com/adokter/bioRad/blob/65fbeb0e22090d968c2d9657b1e2e3da2499a45b/DESCRIPTION#L29

The (likely) only reason we have to bump to 4.0.0 is because of the `evaluate` package. A recent update to that package however, will restore R3.6.0 functionality, so I think we can stick to that too.

#245 implements this:

- Sets minimum version to 3.6.0
- Tests for that version as a GH action
- Has a helper function instead of `...names()` which was only released in R4.0.0

Currently the #245 fails because:

```
* evaluate: Needs R >= 4.0.0
```

Once `evaluate > 0.24.0` is released, we should retry the tests for #245. This PR:
