### ISSUE TITLE
Example package cannot be written

### ISSUE THREAD

**Issue by fkohrt** [frictionlessdata/frictionless-r#256]
Writing the example package fails due to a 404 at <https://raw.githubusercontent.com/frictionlessdata/frictionless-r/main/inst/extdata/observations_1.csv>

```r
frictionless::write_package(frictionless::example_package)
```

This may have been caused by 4f65dc8 + a82f0b2

**Comment by peterdesmet** [comment]
Thanks for reporting @fkohrt, it is indeed caused by that change.

I have just submitted a new version of frictionless ([1.2.0](https://github.com/frictionlessdata/frictionless-r/blob/main/NEWS.md#frictionless-120)) to CRAN that resolves this issue.

- It also updates `example_package` to a function `example_package()`, which allows us to fail more gracefully in the future
- The example package longer relies on remote files.
- `write_package()` now requires you to provide a directory (no longer `"."` by default).

You can wait for the new version to be available on CRAN or install the development version of frictionless from GitHub:

```R
# install.packages("devtools")
devtools::install_github("frictionlessdata/frictionless-r")
```

And changing your code to:

```R
frictionless::write_package(frictionless::example_package(), directory = "your/path")
```
